version: '3.9'

services:

  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: [sh, -c, cd vite-project && npm run watch]

  server:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/app
    depends_on:
      - node
