version: '3.9'

services:

  node:
    image: node:20.9.0-bullseye
    working_dir: /usr/src/app
    volumes:
      - ./web/vite-project:/usr/src/app
    command: /bin/bash -c "npm install && npm run watch"

  server:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/app
    depends_on:
      - node
